### ISSUE TITLE
frpc v0.32.0-1 mipsel_24kc 问题

### ISSUE THREAD

**Issue by NemoAlex** [kuoruan/openwrt-frp#10]
设备：zbt-we826-32M
启动时有一定几率（约为2/3）报错：
```
SIGILL: illegal instruction
PC=0x47a6cc m=0 sigcode=128

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
  runtime/preempt_mipsx.s:40 +0x7c fp=0x1439f0c sp=0x1439e18 pc=0x47a6cc
errors.New(0x97c637, 0x31, 0xaccd70, 0x140e7b0)
  errors/errors.go:59 +0x38 fp=0x1439f20 sp=0x1439f10 pc=0x48ba5c
github.com/pquerna/cachecontrol/cacheobject.init()
  github.com/pquerna/cachecontrol@v0.0.0-20180517163645-1555304b9b35/cacheobject/directive.go:46 +0x3bc fp=0x1439f34 sp=0x1439f20 pc=0x7d7d24
runtime.doInit(0xd91f00)
  runtime/proc.go:5414 +0xcc fp=0x1439f48 sp=0x1439f34 pc=0x451378
runtime.doInit(0xd8f920)
  runtime/proc.go:5409 +0x80 fp=0x1439f5c sp=0x1439f48 pc=0x45132c
runtime.doInit(0xd93de0)
  runtime/proc.go:5409 +0x80 fp=0x1439f70 sp=0x1439f5c pc=0x45132c
runtime.doInit(0xd91ec0)
  runtime/proc.go:5409 +0x80 fp=0x1439f84 sp=0x1439f70 pc=0x45132c
runtime.doInit(0xd939c0)
  runtime/proc.go:5409 +0x80 fp=0x1439f98 sp=0x1439f84 pc=0x45132c
runtime.doInit(0xd94900)
  runtime/proc.go:5409 +0x80 fp=0x1439fac sp=0x1439f98 pc=0x45132c
runtime.doInit(0xd90780)
  runtime/proc.go:5409 +0x80 fp=0x1439fc0 sp=0x1439fac pc=0x45132c
runtime.main()
  runtime/proc.go:190 +0x22c fp=0x1439fec sp=0x1439fc0 pc=0x441d98
runtime.goexit()
  runtime/asm_mipsx.s:651 +0x4 fp=0x1439fec sp=0x1439fec pc=0x479f4c

r0   0x0  r1   0x4
r2   0x8  r3   0x77e29088
r4   0x8ed704 r5   0x1
r6   0x8  r7   0x5
r8   0x908100 r9   0xac33d0
r10  0x8  r11  0x0
r12  0xf6 r13  0x1
r14  0x0  r15  0xf7
r16  0x0  r17  0x15
r18  0xf9 r19  0x0
r20  0x140e7b0  r21  0x140e7b0
r22  0xd91f28 r23  0xdd0000
r24  0x1  r25  0x77f079cc
r26  0x0  r27  0x0
r28  0x77f3d2a0 r29  0x1439e18
r30  0x14000e0  r31  0x48ba5c
pc   0x47a6cc link 0x48ba5c
lo   0x0  hi   0x0
```

v0.31.2-1 正常。或许是FRP本身的原因？

**Comment by kuoruan** [comment]
应该是 OpenWrt golang package 或者 golang 的 BUG

**Comment by botsphp** [comment]
升级到 go14.1再编译就没问题了。
